### ISSUE TITLE
Forest Stories headlines

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#11]
During our meeting, we talked about whether or not we could have the headline for each blog post live only in the body copy and not as an overlay on the hero image. There is also a question of what we can do with the breadcrumbs there - what are our options?

**Comment by ianjwhitmore** [comment]
All options are available. If we remove it from the header do we want it:
1) Automatically added to the content column.
2) Entered as an optional manual header. 

As for breadcrumbs, we could move the breadcrumbs into the top of the content column as well.

**Comment by ianjwhitmore** [comment]
@mfoucht @sarahmagrish 

I worked up a quick alternative template to explore this...

Here is what we have:
http://ianwhitmore.com/clients/ecotrust/nwcf/2017/12/04/5-questions-with-cherie-kearney/

Here is an alternative
http://ianwhitmore.com/clients/ecotrust/nwcf/2017/11/30/blog-post-1-title/

Personally, I think what we have works well and feels more complete (design wise) but I like the clean look of the alternative. 

I hope this helps.

**Comment by sarahmagrish** [comment]
This looks good to me! Thanks

http://ianwhitmore.com/clients/ecotrust/nwcf/2017/12/04/5-questions-with-cherie-kearney/


--
Sarah Cline | Design Director | Ecotrust
‪721 NW 9th Avenue, Suite 200 |  Portland, OR 97209<x-apple-data-detectors://11/1>
‪M (971) 344.7595<tel:(971)%20344.7595> | www.ecotrust.org<http://www.ecotrust.org/>

Please note that I am out on Fridays.

**Comment by mfoucht** [comment]
Ditto what @sarahmagrish said - Looking like a much tighter layout. Thanks!

**Comment by ianjwhitmore** [comment]
Great! We’ll keep it as is.
