### ISSUE TITLE
Call to actions on Homepage

### ISSUE THREAD

**Issue by ianjwhitmore** [ianjwhitmore/ecotrust-northwest-community-forests#14]
I added buttons to the top three box on the homepage for two reasons:

1) To create clearer prompt to the user 
2) Ease is edting for you and the client. Manually linking the text and icon is pretty tedious.

Let me know your thoughts? We can set the button language to anything you want.

**Comment by sarahmagrish** [comment]
love them! thank you.

**Comment by mfoucht** [comment]
Yes! really like that - thanks!

**Comment by ianjwhitmore** [comment]
Awesome!
