### ISSUE TITLE
Events 

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#15]
What happens when there are no events? Does it disappear on the homepage? Or do past events show up?

**Comment by ianjwhitmore** [comment]
Will test ASAP, currently past events show up.

**Comment by mfoucht** [comment]
Ok thanks!

**Comment by ianjwhitmore** [comment]
I have this sorted out now. I changed the template to only show posts that are set for a future date so you don't have to manually go in and manage them by category. If there are actually no future events it will display a message. 

We can make this messaging anything you want. I have something in there now. 

Let me know how this looks on your end.

**Comment by mfoucht** [comment]
Ok thanks - Please use the following text:

(subhed)
Check out these events happening throughout the region to connect with community forests in your area.

(default text for no events)
Stay tuned! We'll share more upcoming events soon.

**Comment by mfoucht** [comment]
Also, one more piece on this: the hover color of the button on the homepage needs to be updated. Thanks!

**Comment by ianjwhitmore** [comment]
Text updated and colors updated.
