### ISSUE TITLE
 Update PDF icons on the Your Forest page

### ISSUE THREAD

**Issue by sarahmagrish** [ianjwhitmore/ecotrust-northwest-community-forests#16]
Hi Ian, Can we add three different varieties of PDF icons to the "Your Forest" page for the three different classes? Looking to customize the look of that page a bit but don't want to make a ton more work for you. thx!

**Comment by ianjwhitmore** [comment]
Yes, can you tell me what you want those to be and send them over as vector files? The sooner the better. 

@hbdelacruz just want to make you see this so you can coordinate with Sarah on this too.

**Comment by sarahmagrish** [comment]
Totally! @hbdelacruz -- we were thinking about how the "Your Forest" page can feel a little more branded and I was thinking that maybe you could design three different icons / little round illos that correspond with the types of info people might download? I don't think we need to use the word "PDF" in the icon at all since that can be in the title if it is needed or perhaps no one cares with the file type is anyways -- they just want to know it is a downloadable file that will help them learn what they want to know. Sound ok with your hours? thx!

**Comment by mfoucht** [comment]
We have new icons for the top three boxes too, right?

**Comment by ianjwhitmore** [comment]
@mfoucht Added the icons to the top three boxes. 
@sarahmagrish still waiting on the three different PDF icons.

**Comment by hbdelacruz** [comment]
Re-reading this, realizing it's more custom icons we are wanting. Will cook up a few options today, and Ian I will shoot you an email when I get them in the icon folder. Thanks!

**Comment by hbdelacruz** [comment]
@ianjwhitmore Icons are now in the icon folder

**Comment by ianjwhitmore** [comment]
New PDF Images are added and are now available in the media library. @mfoucht it looks like you were able to add a PDF and add the link successfully.

**Comment by mfoucht** [comment]
Yes! I think I have it figured out.
