### ISSUE TITLE
About Page - Member logos

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#17]
Client expressed that they would like to see member logos on the About page as well, but possibly a different treatment than the greyed out logos that we have on the home page. 

Helday / @sarahmagrish - your thoughts on where a "Meet our Members" section should go on that page?

**Comment by ianjwhitmore** [comment]
We can add the same kind of slider/carousel of images and they can be color or greyed out.
Just let me know. I'll drop in a placeholder for now.

**Comment by mfoucht** [comment]
OK - are there any parameters on how many logos can be shown? It sounded like they would like to see more than 3 at a time.

**Comment by ianjwhitmore** [comment]
We can adjust that, I would suggest a max of 6, and then it will show less on smaller screens, perhaps 4 on tablet and 2 on phone.

**Comment by mfoucht** [comment]
Ok that sounds good to me - it looks like there are only 6 partner logos to include so hopefully we'll be able to get the full group in there.

**Comment by ianjwhitmore** [comment]
Checkin on this as well. I still need the "gray" treated logos for the partner logos and the member logos.

**Comment by hbdelacruz** [comment]
@ianjwhitmore grey logos are in the logo folder now!

**Comment by ianjwhitmore** [comment]
Added these, the carousel isn’t behaving as expected. On mobile the logos scale down to be very very small. 

It might be better to put these in a grid of images. Three across and then two across underneath?

Are you all open to that? Then we can set them to stack on smaller screens.

**Comment by sarahmagrish** [comment]
Sounds just fine to me!
--
Sarah Cline | Design Director | Ecotrust
‪721 NW 9th Avenue, Suite 200 |  Portland, OR 97209<x-apple-data-detectors://11/1>
‪M (971) 344.7595<tel:(971)%20344.7595> | www.ecotrust.org<http://www.ecotrust.org/>

Please note that I am out on Fridays.

**Comment by mfoucht** [comment]
Yes, fine with me too! And we should be sure and link those logos to the corresponding member websites. I can help with that.

**Comment by ianjwhitmore** [comment]
These are sorted out now. A row of five for desktop/tablet and the below tablet they drop into a stacked column. @mfoucht you can go in and link these up or send me the URLs if you like. They essentially the same as the PDF elements on the YF page.
