### ISSUE TITLE
About Page - Map of Community Forests

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#18]
@ianjwhitmore - The client would eventually like to have an iframe of a map that is dynamically populated via ArcGIS online, but they're working through getting their profile set up. In the mean time, we have a static image of a map with community forests, but many of them are quite small. Is there a way we could include that image, but have some kind of in-page zoom functionality?

**Comment by ianjwhitmore** [comment]
The easiest way would be with a plugin, I think.

**Comment by ianjwhitmore** [comment]
Can you find an example of what you're expecting somewhere online and post a link?

**Comment by mfoucht** [comment]
I think something like this would work: https://wordpress.org/plugins/wp-image-zoooom/

**Comment by ianjwhitmore** [comment]
@mfoucht I add that plugin and did a quick set up for the map. It works pretty well! 

There are a few settings that have to be applied but if you provide a final map image we can drop it in.

**Comment by mfoucht** [comment]
yes - that does look good! Should I attach the map image here?

Also - did the plug in somehow cause the logos to disappear??

**Comment by ianjwhitmore** [comment]
Added and updated! I accidentally deleted the placeholder logos, they are added back. 

I also added a button element to download the map.

**Comment by mfoucht** [comment]
@sarahmagrish and @hbdelacruz - realizing that I should have brought you in on this since it's a design element. What do you think of the solution we've implemented here? It's kind of a stop-gap before the next iteration.
