### ISSUE TITLE
Press / PR

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#20]
- Looks like Press / PR is missing from right well categories on Forest Stories page
 - Client would like to see Press / PR called out in the footer (under Forest Stories?) as well - possible?

**Comment by ianjwhitmore** [comment]
The right sidebar only shows categories that have posts. This will automatically update when PR posts are added. 

I added this to the Footer menu which is not automatically updated based on posts or no posts.

**Comment by mfoucht** [comment]
Ah yes - thanks for the reminder. Once I get a login from you I'll update the Press/PR category.
