### ISSUE TITLE
Mobile styling

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#22]
A couple notes,  but mostly a question: Did we leave you enough time to address mobile issues? Or should the theme be pretty dynamic in this case and already be mobile optimized.

The couple of things I noticed were:
- It looks like only some of the images with the header text are appearing appropriately. For example, the header image on the About page is cutting off "Coalition"
 - Looks like any left-aligned text doesn't leave any margin on mobile. 
 - client is most concerned about events, which look great on mobile!

**Comment by ianjwhitmore** [comment]
Mobile corrections should be minimal overall. I can look at these issues and I will go through the site on mobile and tablet as well.

**Comment by ianjwhitmore** [comment]
Cleaning things up here and there ... will keep polishing any elements that look awkward.

**Comment by sarahmagrish** [comment]
@hbdelacruz can you please cruise the mobile version of the site on your phone and log any additional edits before we close down new issues Thursday? thx!

**Comment by hbdelacruz** [comment]
Sure thing

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hbdelacruz** [comment]
@ianjwhitmore @sarahmagrish Lookin' good to me! The only two things I noticed on mobile, and I'm not sure how big of a deal they are these: 1) The ecotrust logo seems to get squished up next to MARS logo on the About page. 2) Under Contact, the Address line seems to disconnect from the icon.
![file](https://user-images.githubusercontent.com/18173346/34270555-6bfb892a-e63d-11e7-8d7c-f1d96655d7f4.png)
![file1](https://user-images.githubusercontent.com/18173346/34270556-6c138ad4-e63d-11e7-92a1-3a7f5ce8e489.png)

**Comment by ianjwhitmore** [comment]
Both of these should be addresses and worked out now. I set the contact page to center it's content below tablet screen size so there are less awkward alignment issues on all the various sizes of phone screens out there.
