### ISSUE TITLE
Events button on Homepage

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#23]
Looks like it's not going any where yet. @ianjwhitmore - am I recalling correctly that you're looking to us for where we want that to go??

**Comment by mfoucht** [comment]
Also thinking that button should follow the styling of the rest of the buttons on the homepage, right @sarahmagrish?

**Comment by mfoucht** [comment]
I think something like this would work: https://wordpress.org/plugins/wp-image-zoooom/

**Comment by ianjwhitmore** [comment]
Set this button to match, also I set a rule to make all buttons all caps for consistency and legibility.
