### ISSUE TITLE
Dates are buggy on blog

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#26]
Looks like there is something wonky going on in the code that is pulling the month number in place of the day date. So the Press / PR piece that I just posted shows August 8 as the date even though the publication date is set to August 3.

**Comment by ianjwhitmore** [comment]
Fixed! Very weird but the code was putting in the month as the day numerically so all june posts were on the 06th and august on the 08th and so on.
