### ISSUE TITLE
Option to edit blog preview?

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#27]
What are our options for showing specific copy in the blog post preview text that shows up in the grid blocks?? Right now it's auto-populating with the first info in the post, but I'm not a huge fan of things like author attribution etc. showing up in those blocks.

**Comment by ianjwhitmore** [comment]
Try the "Excerpt" entry further down on the page. Let me know if you can't see it for some reason. 
The code will look for an excerpt first then pull from the start of the post.

**Comment by mfoucht** [comment]
OK - it's not currently showing up for me as an option. Am I selecting the right kind of post?

**Comment by ianjwhitmore** [comment]
Ah, check the "Screen Options" tab in the upper right hand of the page. You may have to select 'excerpt to see it. Let me know if that works?

**Comment by ianjwhitmore** [comment]
@mfoucht ... hello, were you able to locate this so you can set the excerpt?

**Comment by ianjwhitmore** [comment]
@mfoucht any updates on this?

**Comment by mfoucht** [comment]
Ack- sorry for the delayed response! I found the excerpt option in the editor. But it doesn't look like it's pulling the text that I include in there...

**Comment by ianjwhitmore** [comment]
This should be ready to go. If there is an excerpt entry it will display, if not it will default to the the shorted first part of the content.

**Comment by mfoucht** [comment]
yep! Looks great. Definitely have to be mindful of length on these since the blocks behave differently depending on the length of the excerpt
