### ISSUE TITLE
Your Forest page spacing

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#34]
@hbdelacruz and @sarahmagrish - what are your design thoughts on the spacing of the Your Forest page? I feel like there's a whole lot of space, but am curious to hear your thoughts on the matter.

**Comment by sarahmagrish** [comment]
yes agreed! It feels too open to me too.

**Comment by ianjwhitmore** [comment]
We need the spacing if you want the smooth scroll from the menu otherwise it will scroll to the top of the section and the header will be hidden.

I can see if it’s possible to reduce it and offset the scroll to match.

**Comment by sarahmagrish** [comment]
Again, doesn’t feel urgent to me.
--
Sarah Cline | Design Director | Ecotrust
‪721 NW 9th Avenue, Suite 200 |  Portland, OR 97209<x-apple-data-detectors://11/1>
‪M (971) 344.7595<tel:(971)%20344.7595> | www.ecotrust.org<http://www.ecotrust.org/>

Please note that I am out on Fridays.
