### ISSUE TITLE
"read more" link in forest stories posts

### ISSUE THREAD

**Issue by sarahmagrish** [ianjwhitmore/ecotrust-northwest-community-forests#36]
thinking that link should probably open in a new browser window and have an icon to set that expectation—http://fontawesome.io/icon/external-link/?

**Comment by ianjwhitmore** [comment]
Just to double check do you any link that is set to open in a new window to have this after the text? 
I can try to do this through CSS and jQuery otherwise it requires adding this symbol manually somehow. 

Do we want to make this general style rule for external links?

**Comment by sarahmagrish** [comment]
Yes that would be great – thx!
--
Sarah Cline | Design Director | Ecotrust
‪721 NW 9th Avenue, Suite 200 |  Portland, OR 97209<x-apple-data-detectors://11/1>
‪M (971) 344.7595<tel:(971)%20344.7595> | www.ecotrust.org<http://www.ecotrust.org/>

Please note that I am out on Fridays.

**Comment by ianjwhitmore** [comment]
@sarahmagrish Can you point me in the direction of an external link that is in one of the forest stores. If you are referring to the 'Read More' link that open the full forest story I would recommend against opening a new window. It typically isn't best practices to open content from the same site in new windows.

**Comment by sarahmagrish** [comment]
Oh the read more link I visited took me to a different site -- it was a Eugene weekly paper. Not at my laptop right now tho hence no link!

I would consider that a different site, wouldn't you?

Sarah Cline | Design Director | Ecotrust
721 NW 9th Avenue, Suite 200 |  Portland, OR 97209<x-apple-data-detectors://11/1>
M (971) 344.7595<tel:(971)%20344.7595> | www.ecotrust.org<http://www.ecotrust.org/>

Please note that I am out on Fridays.

On Dec 21, 2017, at 12:59 PM, ianjwhitmore <notifications@github.com<mailto:notifications@github.com>> wrote:


@sarahmagrish<https://github.com/sarahmagrish> Can you point me in the direction of an external link that is in one of the forest stores. If you are referring to the 'Read More' link that open the full forest story I would recommend against opening a new window. It typically isn't best practices to open content from the same site in new windows.

**Comment by ianjwhitmore** [comment]
Absolutely, I just need to know which post you're looking at. Most of these don't have external links so I haven't found it yet.

**Comment by mfoucht** [comment]
@sarahmagrish and @ianjwhitmore - I think I can go through and fix these

**Comment by ianjwhitmore** [comment]
Added, this will only work on single stories pages because it will cause unexpected results on pages like "Your Forests" with all of the PDFs.
