### ISSUE TITLE
events

### ISSUE THREAD

**Issue by sarahmagrish** [ianjwhitmore/ecotrust-northwest-community-forests#37]
can we have the default display be list instead of calendar? i think that will be more relevant since they won't have a ton of events.

**Comment by ianjwhitmore** [comment]
I need to look at where this is in the theme. 
We haven’t looked at the list version and I’m a little worried about the time left. 

I’ll see what I can figure out tomorrow.

**Comment by sarahmagrish** [comment]
Ok — not super urgent in general!
--
Sarah Cline | Design Director | Ecotrust
‪721 NW 9th Avenue, Suite 200 |  Portland, OR 97209<x-apple-data-detectors://11/1>
‪M (971) 344.7595<tel:(971)%20344.7595> | www.ecotrust.org<http://www.ecotrust.org/>

Please note that I am out on Fridays.

**Comment by ianjwhitmore** [comment]
I took a look at the Event List option and it need more work than I believe we have time for today. If we can stick with the calendar for now we could always look at alternatives in future phases.
