### ISSUE TITLE
Home Page Links

### ISSUE THREAD

**Issue by ianjwhitmore** [ianjwhitmore/ecotrust-northwest-community-forests#38]
@mfoucht where would we like the "Get Started" button to go to? 
(The button at the top of the home page.)

**Comment by mfoucht** [comment]
My original idea was that this would go to the Your Forest page. But now I'm wondering if that makes sense from a UX perspective?? Any thoughts from your end?

**Comment by ianjwhitmore** [comment]
I think that makes sense. Those documents (PDFs) are the most direct route to "Getting Started" by comparison to the rest of the site's content.

**Comment by ianjwhitmore** [comment]
Updated!
