### ISSUE TITLE
Contact page edits

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#4]
- Contact information on the right hand side of the page should be:
Address
1130 SW Morrison Street, Suite 510
Portland, OR 97205

Email
info@sustainablenorthwest.org

Phone (no fax)
(503) 221-6911

 - Please edit the donate call to action below to read "Support the Coalition"

**Comment by ianjwhitmore** [comment]
Updated!
