### ISSUE TITLE
past events need deleting

### ISSUE THREAD

**Issue by sarahmagrish** [ianjwhitmore/ecotrust-northwest-community-forests#40]
hi guys! there are some theme events left in there -- see http://ianwhitmore.com/clients/ecotrust/nwcf/events/list/?tribe_paged=1&tribe_event_display=past.

possible for you to delete megan? we should def get those out of there in advance of launch. 

thx,
sarah

**Comment by ianjwhitmore** [comment]
Deleted! Good catch. I am deleting other content that was pre-populated with the theme installation as well.
