### ISSUE TITLE
Coalition Steering Committee Meeting event info

### ISSUE THREAD

**Issue by sarahmagrish** [ianjwhitmore/ecotrust-northwest-community-forests#43]
Hi Megan,

no location there -- is that private by design? If so can they list a contact?

thx!

**Comment by mfoucht** [comment]
Hmm strange - I definitely included a location. But it looks like it disappeared!

**Comment by ianjwhitmore** [comment]
I checked and you should be able to add a location name and address if you like. Might not have saved? 

@mfoucht Do you want to add it back to the site after soft launch? You'll have the same login that you can use.
