### ISSUE TITLE
one blank PDF to delete

### ISSUE THREAD

**Issue by sarahmagrish** [ianjwhitmore/ecotrust-northwest-community-forests#44]
http://ianwhitmore.com/clients/ecotrust/nwcf/your-forest/

last one under managing land

**Comment by mfoucht** [comment]
OK if we leave this one blank? I was going to use it to train Ben on adding / editing these resources.

**Comment by sarahmagrish** [comment]
Oh def! Sorry : )


--
Sarah Cline | Design Director | Ecotrust
‪721 NW 9th Avenue, Suite 200 |  Portland, OR 97209<x-apple-data-detectors://11/1>
‪M (971) 344.7595<tel:(971)%20344.7595> | www.ecotrust.org<http://www.ecotrust.org/>

Please note that I am out on Fridays.
