### ISSUE TITLE
Your Forest page

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#5]
The three blocks at the top should have the following copy:

The Basics
What is community forestry?
Download the resources below to learn more about the basics of
community forests, determine what model is right for you, and determine next steps. 

Buying / Financing Forests
Money matters for future forest owners and supporters
Buying forestland comes with its own complexities and considerations. Download the resources below for guidance on assessing property attributes and financing options

Managing Land
Getting the outcomes you want
Whether managing for recreation or revenue or both, forests can provide a myriad of opportunities for communities.

I think we should combine Buying and Financing, eliminating one of the section of resources on this page.

**Comment by mfoucht** [comment]
Also, please give some attention to these headers. Some of them are capped and some are title case.

**Comment by ianjwhitmore** [comment]
Finished this up and linked the header to scroll down. 

@mfoucht I would suggest a copy edit to keep the headers for these top boxes to one line...

Perhaps "Forest Financing", "Forest Finances", "Buying / Financing"

**Comment by mfoucht** [comment]
Looks good - thanks!
