### ISSUE TITLE
favicon needs updating

### ISSUE THREAD

**Issue by sarahmagrish** [ianjwhitmore/ecotrust-northwest-community-forests#6]
Not a beta requirement but the favicon needs updating. Helday, can you create one for Ian?

**Comment by ianjwhitmore** [comment]
I just whipped one of these up, put the branches in white over the light green. We can swap out with whatever you like.

**Comment by hbdelacruz** [comment]
working on one now!

**Comment by ianjwhitmore** [comment]
@hbdelacruz any updates on this?

**Comment by hbdelacruz** [comment]
Yeah, working on a few options to send today!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ianjwhitmore** [comment]
Great, please send as soon as you can. We really need to have all assets completed.

**Comment by hbdelacruz** [comment]
favicon options are in the icons folder

**Comment by ianjwhitmore** [comment]
Updated!
