### ISSUE TITLE
Forest Stories: uncategorized

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#9]
When I click on Uncategorized, the categories disappear from the right hand well. Also, can we edit this to be titled something other than Uncategorized? 

Also possible for Forest Stories to NOT appear as a category option? Or maybe call it All Stories when it appears as an option in that right hand well?

**Comment by ianjwhitmore** [comment]
Uncategorized will go away when the placeholder posts are deleted. Sorry, should have already removed those.

**Comment by ianjwhitmore** [comment]
Uncategorized posts are removed and this category was changed to Press / PR to avoid future confusion.
